services:
  siffle-server:
    image: siffle
    command: server
    networks:
      - siffle-net
  siffle-client:
    image: siffle
    command: tcp -s siffle-server --mps 100 -t 20
    depends_on:
      - siffle-server
    networks:
      - siffle-net
networks:
  siffle-net:
    driver: bridge
