services:
  siffle-server:
    image: siffle
    command: server
    environment:
      - RUST_LOG=INFO
    networks:
      - siffle-net
  siffle-client:
    image: siffle
    command: udp -s siffle-server --mps 1000 -t 20
    environment:
      - RUST_LOG=INFO
    depends_on:
      - siffle-server
    networks:
      - siffle-net
networks:
  siffle-net:
    driver: bridge
